### ISSUE TITLE
Wrong header generated when compiling

### ISSUE THREAD

**Issue by Psy-Kai** [emqtt/qmqtt#152]
When compiling qmqtt with qmake the generated header just look like this:

    #include "../../../src/mqtt/qmqtt_client.h"
The problem is really hard to find because the Qt qmake features (*.prf) are used. But Qt warns in this feature-files that they could change at any time. So using them is a very very bad idea. So for now you cannot build a usable developer version of qmqtt with newer Qt-versions (I tested 5.9 and 5.10) using qmake.

**Comment by mwallnoefer** [comment]
Okay, this seems to be a valid issue. I assign this to @KonstantinRitt, which converted the library into a Qt module - he is more expert in this area.

**Comment by KonstantinRitt** [comment]
> The problem is really hard to find <snip>

*Which* problem?
Did you configure your Qt with -developer-build? If so, how do the other Qt module's headers look like? Otherwise, did you try `make install`?

**Comment by Psy-Kai** [comment]
Okay. `make install` "solved" the problem.
But since qmqtt is no official Qt module I don't like the idea that its files are installed into the Qt directories by default. Is it possible with a small qmake argument to define an other install dir?

**Comment by KonstantinRitt** [comment]
It is how Qt modules work, "official" or not. It doesn't matter if some one likes or dislikes that.

> Is it possible with a small qmake argument to define an other install dir?

Yes. Configure your Qt with -developer-build, build qtbase (and all other modules of interest) with just `make` instead of `make install`. Note that this option is for developing Qt, not *with* Qt, which means you likely do not want to deploy your final binaries to the store.

**Comment by KonstantinRitt** [comment]
Plz close this issue as "Invalid/Won't fix"

**Comment by mwallnoefer** [comment]
Okay, as far as I have understood choosing another module installation path for qmqtt is very complicated due to design limitations in Qt itself.

@Psy-Kai If you disagree with this you need to find your own work-around. Maybe integrate the library (at least the headers) in your project to have the headers in a handy path. That is all what I can suggest you, I am afraid.
