### ISSUE TITLE
Bitbake/yocto recipe for qmqtt

### ISSUE THREAD

**Issue by tomasz3dk** [emqtt/qmqtt#166]
Didn't know where to announce that, so i've created new issue. I've made a bitbake recipe for qmqtt, and maybe it's worth to include it here in qmqtt sources or somewhere else. that someone who wants to use this library in embedded device that is developed with yocto project have everything in one place.
Link to recipe:
https://github.com/tomasz3dk/meta-cpplibs/blob/master/recipes-devtools/qmqtt/qmqtt_git.bb

**Comment by mwallnoefer** [comment]
Hi @tomasz3dk, first a big thank-you for your efforts.

@emqtt/qmqtt-team Has anyone a clear opinion about the inclusion of a Yocto bitbake receipt directly into our repo? Or should it better be maintained elsewhere?

**Comment by ejvr** [comment]
Unfortunately my experience with these kind of recipes is rather limited. What I have seen is that the recipes are kept in a separate repository (the repository maintained by the distribution manager). One of the reason was that the recipe contains the download url of the source of the package, so the package builder knows where to find the source (and also which tag/version to use).

The only reason I can imagine to include the recipe here, is to make it easy for maintainers to include qmqtt in their own bitbake derived distribution.

**Comment by diegorondini** [comment]
> Didn't know where to announce that, so i've created new issue. I've made a bitbake recipe for qmqtt, and maybe it's worth to include it here in qmqtt sources or somewhere else. that someone who wants to use this library in embedded device that is developed with yocto project have everything in one place.
> Link to recipe:
> https://github.com/tomasz3dk/meta-cpplibs/blob/master/recipes-devtools/qmqtt/qmqtt_git.bb

Hi @tomasz3dk . I think the best place for such a recipe would be to contribute it to meta-qt5:
https://github.com/meta-qt5/meta-qt5

**Comment by tomasz3dk** [comment]
Hi @diegorondini . Good point :). Thanks. I'm closing this issue.
