### ISSUE TITLE
How to specify a network adapter

### ISSUE THREAD

**Issue by singoo** [emqtt/qmqtt#169]
I used this lab, but I don't know how to specify a network adapter.
There are three network cards on my hardware, RJ45 and 4G.
So I need to specify a network adapter to send and receive messages.

**Comment by mwallnoefer** [comment]
These are topics which are absolutely not covered by Qt and qmqtt in particular, since they belong to the domain of the underlying OS. You would need to properly configure the IP routes (_route_ command) so that the Mqtt traffic directed to the broker travels correctly.

I would suggest you to ask someone for help if you are not familiar with network configuration stuff in your OS.
