### ISSUE TITLE
Build MQTT for android on QT Creator

### ISSUE THREAD

**Issue by tranvinhphuc111996** [emqtt/qmqtt#171]
I have problem when try to build mqtt on Android. But it work well when i using that problem on desktop of Qt ! 
Error notified is ":-1: error: Unknown module(s) in QT: mqtt"

**Comment by ejvr** [comment]
The error you mention usually pops up if by build qmqtt but do not install afterwards. After running 'qmake' and 'make' you should also run 'make install'.

I'm not sure how if an android build requires special actions though.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tranvinhphuc111996** [comment]
im install step by step in this stackoverflow 
https://stackoverflow.com/questions/48701475/qt-creator-adding-mqtt-library

**Comment by ejvr** [comment]
The article on stackoverflow is not about this library. There are two mqtt implementations for QT. This one (installed as qmqtt) is the oldest.

Last year the QT organization also provided a mqtt implementation (installed as mqtt). The stackoverflow explains how to install the QT implementation, nor ours.

However, it you want to use this library you can follow the same instruction. Of course, the download location is difference and in the project file you have to use 'QT += qmqtt' instead of 'QT += mqtt'

**Comment by tranvinhphuc111996** [comment]
okey thanks for your help, i try to build qmake of armv7 for this library and now have a new problem is "/bin/sh: 1: Syntax error: "(" unexpected"

**Comment by ejvr** [comment]
Hmm, cross compiling QT. Never did that with QT 5.

I'm sorry, I can't help you there. And it's outside of the scope of this library. Maybe someone of the QT forums can help you.
