### ISSUE TITLE
Impossible to connect host

### ISSUE THREAD

**Issue by audicm2** [emqtt/qmqtt#175]
Hi, MQTT is new for me, i'm a beginner. So sorry for my question...

I have download "Mosquitto" to have a broker and "Mosquitto_client" to sub and pub.

Now, with qt, i want create an client and connect me to host and publish a message. So i have the qmqtt library.

This is my code :

`
#include <QCoreApplication>
#include <iostream>
#include <qmqtt.h>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    QMQTT::Client *client = new QMQTT::Client(QHostAddress("192.168.0.4"), 1883);
    client -> connectToHost();

    if (client -> connectionState() == QMQTT::ConnectionState::STATE_CONNECTED)
    {
       std::cout<<"Connected"<<std::endl;

    }

    else if (client -> connectionState() == QMQTT::ConnectionState::STATE_CONNECTING)

    {
      std::cout<<"Connecting"<<std::endl;
    }

    else {

      std::cout<<"Deconnected"<<std::endl;

         }

    //client ->subscribe("test");
    client ->publish(QMQTT::Message(1,"test","Hello"));

    return a.exec();
}
`

Thanks for your answer !

**Comment by mwallnoefer** [comment]
No, this won't work, since the connection state needs to be checked in an asynchronuous callback (signal-slot). Please have a look at our code example https://github.com/emqtt/qmqtt/blob/master/examples/qmqtt/client/example.cpp to understand what needs to be fixed.

If you think that the locally installed Mosquitto broker doesn't work properly I highly suggest you to install some other mqtt client (a GUI: https://github.com/mqtt/mqtt.github.io/wiki/tools) to double-check.

**Comment by audicm2** [comment]
Hi mwallnoefer,

Ok thanks, it's do work ! But i don't understand all the code.

If i want publish just one message like "Hello", How i do ? i want to understand with something simple.

And how to work connect() function ? 

Thanks for your answer !

**Comment by mwallnoefer** [comment]
You may just consider the _Publisher_ class with the _onConnected()_ handler (raised by the _connected()_ signal) wherein you just call the _publish_ method. That means something like this:
```
void onConnected()
{
      publish(message); // if successful raises a published() signal
}
```

Then register an _onPublished_ handler where at the end you call _disconnectFromHost()_

```
connect(this, &Publisher::published, this, &Publisher::onPublished);

void onPublished(const quint16 msgid, const quint8 qos)
{
      disconnectFromHost(); // if successful raises a disconnected() signal
}
```

You see everything works asynchronously over Qt's event queue.

**Comment by audicm2** [comment]
Hi mwallnoefer,

Ok thanks for all, i understand now, in looking for my side also yesterday and with your explications.

Now, i have a last question. If i want create a Web page annd send data with QMQTT, it's possible ? May be with WebSocket ? (I use always the same broker : Mosquitto). But i don't know how to create Web Page et make the connexion with QMQTT.

Thanks for you answer !

**Comment by mwallnoefer** [comment]
The assumption that WebSockets would be the right decision if you develop a web-based mqtt client is correct, since then you generally make use of the ports 80 and 8080 which in the major part of the cases are not blocked by firewalls. This in contrast to the mqtt(s) protocol which works on port 1883 and therefore requires explicit permission rules, especially in company networks.

qmqtt understands both the mqtt and the WebSocket protocol as shown in the README file. But the major show-stopper comes here: it won't be easy to develop a Qt-based web client or web server...let's say that in this case Qt is not the best option.

So if you ask me I would go with something like MQTT.js (https://github.com/mqttjs/MQTT.js) which works also in a browser client-side.

**Comment by audicm2** [comment]
Ok i understand.

So it's possible to create a client qmqtt to publish to mosquitto and an client MQTT.js to retrieve data send by qmqqt and send this data to a Web Page ?

Thanks for your answer !

**Comment by mwallnoefer** [comment]
yes.
