### ISSUE TITLE
Incoming MQTT message corruption

### ISSUE THREAD

**Issue by sprout42** [emqtt/qmqtt#58]
I have an application that is receiving many MQTT messages very quickly.  And in one particular instance I found that it looked like the message data from multiple messages was being treated as the payload for a single message.

I was able to "fix" the issue by removing the QDataStream translation from the "void QMQTT::Network::onSocketReadReady()" function.  I am not really sure why the QDataStream translation would cause such a problem, but this solved the problem for me.

My patch is attached.

[qmqtt_network_corruption.patch.txt](https://github.com/emqtt/qmqtt/files/172748/qmqtt_network_corruption.patch.txt)

**Comment by helmut-muelner** [comment]
I am not sure if you really fixed the problem. I think the bug was introduced with commit c0028ee5261764adeab001fdced5f2b376470088 on Jan, 17 2016 when the member variable _leftSize was renamed to bytesRemaining and moved as a local variable to Network::onSocketReadReady(). This assumes that one can always read complete frames while looping in this function. Moving bytesRemaining back as a member of Network solved the issue for me. I also eliminated all "QDataStream"s from the code because they are not needed.

**Comment by sprout42** [comment]
That is quite possibly the correct fix.  I do very little C++ anymore, and even less QT programming, so I am not familiar with this framework and the implications of the different classes.

**Comment by mwallnoefer** [comment]
I guess this has been fixed in the meantime, should be closed.
