### ISSUE TITLE
Recommended way to run unit tests

### ISSUE THREAD

**Issue by george-hopkins** [emqtt/qmqtt#91]
I have some troubles running the tests with the updated/simplified build system. What is the recommended way to run all unit tests?

Things I already tried:
* `qmake && make`: No tests built
* `qmake "QT_BUILD_PARTS += tests" && make`: Testcases are built but `qmqtt_tests` fails because `libmqtt.so` can not be found (which should be found automatically now)

**Comment by mwallnoefer** [comment]
@emqtt/emqttd-dev-team I am not the expert in this area, could anyone else respond?

**Comment by ejvr** [comment]
This is an old issue, but I ran across the same problem when working on the qmqtt code.
It seems that the unit tests are using classes from qmqtt which are not exported to the shared library, so the linker will not find them. 

Also, 'private' qmqtt header files cannot be found when compiling the tests (this seems to work when compiling using qbs, but not when using qmake).

I guess this can be fixed by creating a new qmake (.pro) file when includes all files needed (preferably using .pri files) for testing instead of trying to use the shared library. Would that be a good idea?

**Comment by mwallnoefer** [comment]
@george-hopkins Are you happy with the solution provided by @ejvr so that we can close this?

**Comment by mwallnoefer** [comment]
I am closing this, please reopen if we need to deepen this further.
